ALTER TABLE tenants ADD COLUMN requests_per_minute BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tenants ADD COLUMN tokens_per_minute BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tenants ADD COLUMN max_concurrent BIGINT NOT NULL DEFAULT 0;
