// Package tunnel.v1 is the wire contract of the Agent tunnel: a mTLS gRPC
// link that an Agent behind NAT opens outbound to every Gateway replica, plus
// the Registry service that issues the node identity used by those links.
//
// The tunnel carries runtime semantics, never arbitrary HTTP. Every payload in
// this file mirrors a type of common/runtime, so both sides
// can convert to that package's Go types without inventing a second canonical
// model. Agent and Gateway share this one file and its generated code.
//
// Two rules are load-bearing and must survive any future edit:
//   - No message here carries a credential. RuntimeSpec references an API key
//     by name (api_key_ref) and never by value; RuntimeSnapshot mirrors
//     runtime.Snapshot, which is credential-free by construction.
//   - No message here can express "fetch this URL" or "run this command". The
//     Agent is not a general-purpose proxy, and the protocol deliberately
//     leaves no extension point that would make it one.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/proto/tunnel/v1/tunnel.proto

package tunnelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tunnel_Control_FullMethodName = "/tunnel.v1.Tunnel/Control"
	Tunnel_Serve_FullMethodName   = "/tunnel.v1.Tunnel/Serve"
)

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tunnel is implemented by every Gateway replica; an Agent connects to each
// replica separately, so a request never needs forwarding between replicas.
// Both methods require a valid client certificate, and each replica must
// independently check that the node_id in the certificate SAN matches the
// node_id declared on the stream, closing the stream when they differ.
type TunnelClient interface {
	// Control is the long-lived control plane: heartbeats, status reporting,
	// config delivery, replica roster and graceful drain. Exactly one per
	// (Agent, replica) pair.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControl, GatewayControl], error)
	// Serve is one data-plane slot. The Agent opens it, sends Ready and waits;
	// the Gateway dispatches a request into it. A slot serves one request at a
	// time and may send Ready again to be reused afterwards.
	Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, GatewayFrame], error)
}

type tunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelClient(cc grpc.ClientConnInterface) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControl, GatewayControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tunnel_ServiceDesc.Streams[0], Tunnel_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentControl, GatewayControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_ControlClient = grpc.BidiStreamingClient[AgentControl, GatewayControl]

func (c *tunnelClient) Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, GatewayFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tunnel_ServiceDesc.Streams[1], Tunnel_Serve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, GatewayFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_ServeClient = grpc.BidiStreamingClient[AgentFrame, GatewayFrame]

// TunnelServer is the server API for Tunnel service.
// All implementations must embed UnimplementedTunnelServer
// for forward compatibility.
//
// Tunnel is implemented by every Gateway replica; an Agent connects to each
// replica separately, so a request never needs forwarding between replicas.
// Both methods require a valid client certificate, and each replica must
// independently check that the node_id in the certificate SAN matches the
// node_id declared on the stream, closing the stream when they differ.
type TunnelServer interface {
	// Control is the long-lived control plane: heartbeats, status reporting,
	// config delivery, replica roster and graceful drain. Exactly one per
	// (Agent, replica) pair.
	Control(grpc.BidiStreamingServer[AgentControl, GatewayControl]) error
	// Serve is one data-plane slot. The Agent opens it, sends Ready and waits;
	// the Gateway dispatches a request into it. A slot serves one request at a
	// time and may send Ready again to be reused afterwards.
	Serve(grpc.BidiStreamingServer[AgentFrame, GatewayFrame]) error
	mustEmbedUnimplementedTunnelServer()
}

// UnimplementedTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServer struct{}

func (UnimplementedTunnelServer) Control(grpc.BidiStreamingServer[AgentControl, GatewayControl]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedTunnelServer) Serve(grpc.BidiStreamingServer[AgentFrame, GatewayFrame]) error {
	return status.Error(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedTunnelServer) mustEmbedUnimplementedTunnelServer() {}
func (UnimplementedTunnelServer) testEmbeddedByValue()                {}

// UnsafeTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServer will
// result in compilation errors.
type UnsafeTunnelServer interface {
	mustEmbedUnimplementedTunnelServer()
}

func RegisterTunnelServer(s grpc.ServiceRegistrar, srv TunnelServer) {
	// If the following call panics, it indicates UnimplementedTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tunnel_ServiceDesc, srv)
}

func _Tunnel_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Control(&grpc.GenericServerStream[AgentControl, GatewayControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_ControlServer = grpc.BidiStreamingServer[AgentControl, GatewayControl]

func _Tunnel_Serve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Serve(&grpc.GenericServerStream[AgentFrame, GatewayFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_ServeServer = grpc.BidiStreamingServer[AgentFrame, GatewayFrame]

// Tunnel_ServiceDesc is the grpc.ServiceDesc for Tunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.v1.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _Tunnel_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Serve",
			Handler:       _Tunnel_Serve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/tunnel/v1/tunnel.proto",
}

const (
	NodeIdentity_Register_FullMethodName         = "/tunnel.v1.NodeIdentity/Register"
	NodeIdentity_RenewCertificate_FullMethodName = "/tunnel.v1.NodeIdentity/RenewCertificate"
)

// NodeIdentityClient is the client API for NodeIdentity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeIdentity is implemented by the Registry alone, never by a Gateway
// replica: one-shot bootstrap token validation needs strongly consistent
// storage, and the CA private key must not be distributed to data-plane
// replicas.
type NodeIdentityClient interface {
	// Register exchanges a one-time bootstrap token for a node certificate.
	// This is the only method in the whole contract that does not require a
	// client certificate.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// RenewCertificate rotates a node certificate and requires the current
	// certificate to still be valid.
	RenewCertificate(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
}

type nodeIdentityClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeIdentityClient(cc grpc.ClientConnInterface) NodeIdentityClient {
	return &nodeIdentityClient{cc}
}

func (c *nodeIdentityClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NodeIdentity_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeIdentityClient) RenewCertificate(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, NodeIdentity_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeIdentityServer is the server API for NodeIdentity service.
// All implementations must embed UnimplementedNodeIdentityServer
// for forward compatibility.
//
// NodeIdentity is implemented by the Registry alone, never by a Gateway
// replica: one-shot bootstrap token validation needs strongly consistent
// storage, and the CA private key must not be distributed to data-plane
// replicas.
type NodeIdentityServer interface {
	// Register exchanges a one-time bootstrap token for a node certificate.
	// This is the only method in the whole contract that does not require a
	// client certificate.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// RenewCertificate rotates a node certificate and requires the current
	// certificate to still be valid.
	RenewCertificate(context.Context, *RenewRequest) (*RenewResponse, error)
	mustEmbedUnimplementedNodeIdentityServer()
}

// UnimplementedNodeIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeIdentityServer struct{}

func (UnimplementedNodeIdentityServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeIdentityServer) RenewCertificate(context.Context, *RenewRequest) (*RenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedNodeIdentityServer) mustEmbedUnimplementedNodeIdentityServer() {}
func (UnimplementedNodeIdentityServer) testEmbeddedByValue()                      {}

// UnsafeNodeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeIdentityServer will
// result in compilation errors.
type UnsafeNodeIdentityServer interface {
	mustEmbedUnimplementedNodeIdentityServer()
}

func RegisterNodeIdentityServer(s grpc.ServiceRegistrar, srv NodeIdentityServer) {
	// If the following call panics, it indicates UnimplementedNodeIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeIdentity_ServiceDesc, srv)
}

func _NodeIdentity_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeIdentityServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeIdentity_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeIdentityServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeIdentity_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeIdentityServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeIdentity_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeIdentityServer).RenewCertificate(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeIdentity_ServiceDesc is the grpc.ServiceDesc for NodeIdentity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeIdentity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.v1.NodeIdentity",
	HandlerType: (*NodeIdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeIdentity_Register_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _NodeIdentity_RenewCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/tunnel/v1/tunnel.proto",
}

const (
	GatewayDirectory_Join_FullMethodName = "/tunnel.v1.GatewayDirectory/Join"
)

// GatewayDirectoryClient is the client API for GatewayDirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayDirectory is implemented by the Registry alone. Every Gateway
// replica joins it once at startup and keeps the stream open for as long as
// it wants to remain in the roster; the Registry authors GatewayRoster from
// every currently open Join stream and pushes the full roster to all of them
// on any change.
type GatewayDirectoryClient interface {
	Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinRequest, GatewayRoster], error)
}

type gatewayDirectoryClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDirectoryClient(cc grpc.ClientConnInterface) GatewayDirectoryClient {
	return &gatewayDirectoryClient{cc}
}

func (c *gatewayDirectoryClient) Join(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[JoinRequest, GatewayRoster], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayDirectory_ServiceDesc.Streams[0], GatewayDirectory_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinRequest, GatewayRoster]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayDirectory_JoinClient = grpc.BidiStreamingClient[JoinRequest, GatewayRoster]

// GatewayDirectoryServer is the server API for GatewayDirectory service.
// All implementations must embed UnimplementedGatewayDirectoryServer
// for forward compatibility.
//
// GatewayDirectory is implemented by the Registry alone. Every Gateway
// replica joins it once at startup and keeps the stream open for as long as
// it wants to remain in the roster; the Registry authors GatewayRoster from
// every currently open Join stream and pushes the full roster to all of them
// on any change.
type GatewayDirectoryServer interface {
	Join(grpc.BidiStreamingServer[JoinRequest, GatewayRoster]) error
	mustEmbedUnimplementedGatewayDirectoryServer()
}

// UnimplementedGatewayDirectoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayDirectoryServer struct{}

func (UnimplementedGatewayDirectoryServer) Join(grpc.BidiStreamingServer[JoinRequest, GatewayRoster]) error {
	return status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedGatewayDirectoryServer) mustEmbedUnimplementedGatewayDirectoryServer() {}
func (UnimplementedGatewayDirectoryServer) testEmbeddedByValue()                          {}

// UnsafeGatewayDirectoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayDirectoryServer will
// result in compilation errors.
type UnsafeGatewayDirectoryServer interface {
	mustEmbedUnimplementedGatewayDirectoryServer()
}

func RegisterGatewayDirectoryServer(s grpc.ServiceRegistrar, srv GatewayDirectoryServer) {
	// If the following call panics, it indicates UnimplementedGatewayDirectoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayDirectory_ServiceDesc, srv)
}

func _GatewayDirectory_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayDirectoryServer).Join(&grpc.GenericServerStream[JoinRequest, GatewayRoster]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayDirectory_JoinServer = grpc.BidiStreamingServer[JoinRequest, GatewayRoster]

// GatewayDirectory_ServiceDesc is the grpc.ServiceDesc for GatewayDirectory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayDirectory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.v1.GatewayDirectory",
	HandlerType: (*GatewayDirectoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _GatewayDirectory_Join_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/tunnel/v1/tunnel.proto",
}
